/** @format */

// PAGEMANAGER ACTION TYPES
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES'
export const SET_PAGE_PARAMS = 'SET_PAGE_PARAMS'
export const PREV_PAGE = 'PREV_PAGE'
export const NEXT_PAGE = 'NEXT_PAGE'
export const LAST_PAGE = 'LAST_PAGE'
export const FIRST_PAGE = 'FIRST_PAGE'
export const SET_LAST_NEWS_STORY_INDEX = 'SET_LAST_NEWS_STORY_INDEX'
export const SET_LAST_PAGE = 'SET_LAST_PAGE'

// NEWS ACTION TYPES
export const SET_NEWS = 'SET_NEWS'
export const SET_CATEGORY_NEWS = 'SET_CATEGORY_NEWS'
export const SET_COLLECTION_NEWS = 'SET_COLLECTION_NEWS'
export const SET_TOPIC_NEWS = 'SET_TOPIC_NEWS'
export const SET_SEARCH_TOPIC = 'SET_SEARCH_TOPIC'
export const CLEAR_TOPIC_NEWS = 'CLEAR_TOPIC_NEWS'
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED'

// AUTH ACTION TYPES
export const LOG_IN = 'LOG_IN'
export const SET_USER = 'SET_USER'
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT'
export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'

// PARAM ACTION TYPES
export const CLEAR_PARAMS = 'CLEAR_PARAMS'
