// PAGEMANAGER ACTION TYPES
export const PREV_PAGE = "PREV_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const LAST_PAGE = "LAST_PAGE";

// ARTICLES ACTION TYPES
export const SET_ARTICLES = "SET_ARTICLES";
export const SET_CATEGORY_ARTICLES = "SET_CATEGORY_ARTICLES";
export const SET_COLLECTION_ARTICLES = "SET_COLLECTION_ARTICLES";
export const FETCH_CATEGORY_ARTICLES_FAILED = "FETCH_CATEGORY_ARTICLES_FAILED";
export const FETCH_ARTICLES_FAILED = "FETCH_ARTICLES_FAILED";
export const SET_LAST_ARTICLE_INDEX = "SET_LAST_ARTICLE_INDEX";
export const SET_LAST_PAGE = "SET_LAST_PAGE";

// AUTH ACTION TYPES
export const LOG_IN = "LOG_IN";
export const SET_USER = "SET_USER";
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";
export const AUTHENTICATE_USER_FAILED = "AUTHENTICATE_USER_FAILED";